server:
  port: 8083
spring:
  application:
    name: consumer-user
  main:
    allow-bean-definition-overriding: true  # 允许覆盖FeignClient
  datasource:
    username: root
    password: 123@qwe
    url: jdbc:mysql://localhost:3306/test_springboot?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  instance:
    prefer-ip-address: true # 注册时使用服务IP地址注册
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka


feign:
  hystrix: # 提供断路器
    enabled: true