server:
  port: 8001

spring:
  application:
    name: eureka-server
  datasource:
    username: root
    password: 123@qwe
    url: jdbc:mysql://localhost:3306/test_springboot?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka2:8002/eureka

#eureka:
#  instance:
#    hostname: eureka1 # eureka实例主机名
#  client:
#    # 单机：false 集群：true
#    # 不把自己注册到eureka上
#    register-with-eureka: true
#    # 不从eureka上获取服务注册信息
#    fetch-registry: true
#    service-url:
#      # 取值是Map,没有提示信息,单机写自己的服务地址，集群写其他
#      defaultZone: http://eureka1:8001/eureka